- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |     echo ""
          echo "*************** TERRAFOM PLAN ******************"
          
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
