steps:
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  script: |
          #!/usr/bin/env bash

          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
